---
- name: remove rabbitmq virtual hosts
  rabbitmq_vhost:
    node: "{{ rabbitmq_nodename }}"
    name: "{{ item }}"
    state: absent
  with_items: "{{ rabbitmq_vhosts_absent }}"

- name: add rabbitmq virtual hosts
  rabbitmq_vhost:
    name: "{{ item.name | default(item) }}"
    node: "{{ item.node | default(rabbitmq_nodename) }}"
    state: present
    tracing: "{{ item.tracing | default(False) }}"
  with_items: "{{ rabbitmq_vhosts }}"
